---
# Main playbook to install and configure druid services.

- name: Install Druid high performance analytics data store for event-driven data.
  apt:
    name: druid
    allow_unauthenticated: no
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time|default(3600) }}"
    state: present
    install_recommends: yes
  environment:
    RUNLEVEL: 1

- name: Configure Druid common settings.
  template:
    src: common-runtime.properties.j2
    dest: "{{ common_conf_dir }}/common.runtime.properties"

- name: Configure Druid common log4j.properties.
  template:
    src: common-log4j.xml.j2
    dest: "{{ common_conf_dir }}/log4j.j2"

# Configure and launch Coordinator, Historical and Overlord services.
- include_tasks: coordinator.yml
  when: inventory_hostname in groups['persistence']
- include_tasks: overlord.yml
  when: inventory_hostname in groups['persistence']
- include_tasks: historical.yml
  when: inventory_hostname in groups['persistence']
- include_tasks: coordinator.yml
  when: inventory_hostname in groups['persistence']

# Configure and launch Broker and Middlemanager services.
- include_tasks: broker.yml
  when: inventory_hostname in groups['streaming']
- include_tasks: middlemanager.yml
  when: inventory_hostname in groups['streaming']