# This playbook configures vim editor and install the following plugins:
# - name: vim-airline
#   description: vim-airline is a powerful status and tab line for Vim.
#   url: https://github.com/vim-airline/vim-airline
# - name: nerdtree
#   description: The NERDTree is a file system explorer for the Vim editor.
#   install_cmd: vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q
#   default_shortcut: '<F5>'
#   url: https://github.com/preservim/nerdtree
# - name: fzf-vim
#   description: It's an interactive Unix filter for command-line that can be used with any list; files, command history, processes, hostnames, bookmarks, git commits, etc.
#   url: https://github.com/junegunn/fzf.vim
# - name: vim-gitgutter
#   description: A Vim plugin which shows a git diff in the sign column.
#   install_command: vim -u NONE -c "helptags vim-gitgutter/doc" -c q
#   url: https://github.com/airblade/vim-gitgutter
# - name: vim-fugitive
#   description: Fugitive is the premier Vim plugin for Git. Run git command (ie, :Git commit)
#   install_command: vim -u NONE -c "helptags fugitive/doc" -c q
#   url: https://github.com/tpope/vim-fugitive
# - name: vim-floaterm
#   description: Customizable terminal window style.
#   default_shortcut: '<F12>'
#   url: https://github.com/voldikss/vim-floaterm

- name: Config vim
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ansible_env.HOME}}/.vimrc"
    fzf_repo: "https://github.com/junegunn/fzf.git"
    fzf_basedir: '~/.fzf'
    pathogen_artifact: 'https://tpo.pe/pathogen.vim'
  tasks:
    - name: Install required packages on RedHat OS family
      package:
        name:
          - vim-enhanced
          - git
          - powerline-fonts
          - fzf
        state: present
      become: yes
      when: ansible_facts['os_family'] == 'RedHat'
      tags:
        - install_packages

    - name: Install required packages on Debian OS family
      package:
        name:
          - vim
          - git
          - fonts-powerline
        state: present
      become: yes
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - install_packages

    - name: Ensure Fuzzy Finder (fzf) git repo is cloned. Only Debian OS family.
      git:
        repo: "{{ fzf_repo }}"
        dest: "{{ fzf_basedir }}"
        depth: 1
        clone: yes
        update: yes
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - install_packages

    - name: Install Fuzzy Finder (fzf) from source. Only Debian OS family.
      shell: ./install
      args:
        chdir: "{{ fzf_basedir }}"
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - install_packages

    - name: Ensure .vim/{autoload,bundle} directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0755
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"
      tags:
        - configure

    - name: Ensure Pathogen Vim plugin manager is in place.
      get_url:
        dest: "{{ vim_dir }}/autoload/pathogen.vim"
        url: "{{ pathogen_artifact }}"
      tags:
        - configure

    - name: Install plugins.
      git: 
        dest: "{{ vim_dir }}/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
        - name: vim-airline
          url: https://github.com/vim-airline/vim-airline
        - name: nerdtree
          url: https://github.com/preservim/nerdtree
        - name: fzf-vim
          url: https://github.com/junegunn/fzf.vim
        - name: vim-gitgutter
          url: https://github.com/airblade/vim-gitgutter
        - name: vim-fugitive
          url: https://github.com/tpope/vim-fugitive
        - name: vim-floaterm
          url: https://github.com/voldikss/vim-floaterm
      tags:
        - install_plugins

    - name: Ensure .vimrc config in place.
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: yes
        mode: 0640
      tags:
        - configure