---
- name: Add Buanarepo Dev APT-KEY by ID from a Ubuntu Keyserver.
  apt_key:
    keyserver: '{{ ubuntu_key_repository }}'
    id: '{{ buanarepo_dev_key }}'

- name: Make directory tree for Buanarepo CERTS.
  block:
    - name: Checking folders...
      stat:
        path: '{{ item }}'
      register: folder_stats
      with_items:
        - '{{ certs_base }}'
        - '{{ buanarepo_certs_base }}'
        - '{{ buanarepo_restricted_certs_base }}'
    - name: Creating folders for Buanarepo CERTS...
      file:
        path: '{{ item.item }}'
        state: directory
        mode: 0755
        group: root
        owner: root
      when: item.stat.exists == false
      with_items:
        - '{{ folder_stats.results }}'

- name: Configure APT-CONF for accepts HTTPS connections.
  template:
    src: '{{ buanarepo_dev_restricted_template }}.j2'
    dest: '{{ buanarepo_apt_confd }}/{{ buanarepo_dev_restricted_template }}'

- name: Copy CERTS to tarjet hosts.
  copy:
    src: '{{ item }}'
    dest: '{{ buanarepo_restricted_certs_base }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - '{{ buanarepo_dev_ca_restricted_crt }}'
    - '{{ buanarepo_dev_client_restricted_crt }}'
    - '{{ buanarepo_dev_client_restricted_key }}'

- name: Add Buanarepo dev repository.
  apt_repository:
    repo: '{{ buanarepo_dev_restricted_full_path_apt_source }}'
    #repo: deb https://{{ buanarepo_dev_restricted }}/ubuntu xenial {{ repo_type_restricted }}
    state: present
    filename: '{{ buanarepo_dev_restricted }}'
    update_cache: yes
    validate_certs: yes
...