---

##
# Alberto González Mesas, <alberto.gonzalez@euigs.com>
# Mon May 0811 12:40:00 CEST 2020 
##

AWSTemplateFormatVersion: 2010-09-09

##############################################################################################
# Description                                                                                #
##############################################################################################

Description: >
  Creates a CodePipeline pipeline that describes how software changes go through a release process.

##############################################################################################
# Metadata                                                                                   #
##############################################################################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Configure Environment.
        Parameters:
          - AccountName
          - DeploymentGroupName
          - S3BucketArtifacts
          - RegionOfRepositorySource
      - Label:
          default: Configure Pipeline Settings
        Parameters:
          - CodeDeployApplicationName
          - RerunPipelineAfterUpdate
          - CodePipelineServiceRole
          - PipelineForApp
      - Label:
          default: Configure Repository
        Parameters:
          - VersionOfSource
          - RepositorySource
          - BranchOfRepositorySource

##############################################################################################
# Parameters                                                                                 #
##############################################################################################

Parameters:
  AccountName:
    Description: 'The account name, ie euigs-dev-tlt'
    Type: String
    MinLength: 1
  DeploymentGroupName:
    Description: >-
     'The name of an existing CodeDeploy DeploymentGroup to associate this pipeline with.'
    Type: String
    MinLength: 1
  S3BucketArtifacts:
    Description: >-
      The S3 bucket used for storing the artifacts for a pipeline. You can specify the name of an S3 bucket but not a folder 
      in the bucket. 
    Type: String
    Default: euigs-dev-tlt-codepipeline-artifacts-s3
  CodePipelineServiceRole:
    Description: >-
      The Amazon Resource Name (ARN) for AWS CodePipeline to use to either perform actions with no actionRoleArn, 
      or to use to assume roles for actions with an actionRoleArn.
    Type: String
    Default: arn:aws:iam::691268106430:role/service-role/euigs-dev-tlt-codePipelineServiceRole-role
  RegionOfRepositorySource:
    Description: >-
      The action declaration's AWS Region, such as us-east-1.
    Type: String
    Default: eu-west-1
  CodeDeployApplicationName:
    Description: >-
      The name of the CodeDeploy Application Name.
    Type: String
  RerunPipelineAfterUpdate:
    Description: Indicates whether to rerun the CodePipeline pipeline after you update it (boolean).
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  PipelineForApp:
    Description: The name of the application what this pipeline was created.
    Type: String
  VersionOfSource:
    Description: A string that describes the action version.
    Type: String
  RepositorySource:
    Description: Select a codecommit repository.
    Type: String
  BranchOfRepositorySource:
    Description: Select a repository branch from clone and deploy code.
    Type: String

##############################################################################################
# Resources                                                                                  #
##############################################################################################

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: !Sub ${AccountName}-${CodeDeployApplicationName}-pipeline
      ArtifactStore: 
        # The encryption key used to encrypt the data in the artifact store, such as an AWS Key Management Service (AWS KMS) key.
        # If this is undefined, the default key for Amazon S3 is used.
        #EncryptionKey: 
          #EncryptionKey
        Location: !Sub ${S3BucketArtifacts}
        # The type of the artifact store, such as S3.
        Type: S3
      #DisableInboundStageTransitions: 
        # The name of the pipeline in which you want to disable the flow of artifacts from one stage to another.
        #- StageTransition
      RestartExecutionOnUpdate: !Sub ${RerunPipelineAfterUpdate}
      RoleArn: !Sub ${CodePipelineServiceRole}
      # Represents information about a stage and its definition.
      Stages: 
        # Source Stage 1: download from Codecommit
          # The name of the stage.
        - Name: 'Source-stage_clone_from_codecommit_repository'
          Actions:
            # Specifies the action type and the provider of the action.
            - Name: 'Clone_code_from_CodeCommit_Repository_Source'
              RunOrder: 1
              Namespace: SourceNameSpace
              Region: !Sub ${RegionOfRepositorySource}
              ActionTypeId:
                # Valid categories are limited to one of the values below: Source,Build,Test,Deploy,Invoke,Approval.
                Category: Source
                # There are three valid values for the Owner field in the action category section within your pipeline structure:
                # AWS, ThirdParty, and Custom
                Owner: AWS
                # The provider of the service being called by the action. Valid providers are determined by the action category. 
                # For example, an action in the Deploy category type might have a provider of AWS CodeDeploy, which would be specified as CodeDeploy.
                # https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements
                Provider: CodeCommit
                Version: !Sub ${VersionOfSource}
              Configuration:
                RepositoryName: !Sub ${RepositorySource}
                # We recommend that you use CloudWatch Events to detect source changes instead.
                # If you intend to configure a CloudWatch Events rule, you must set PollForSourceChanges to false to avoid duplicate pipeline executions.
                PollForSourceChanges: false
                BranchName: !Sub ${BranchOfRepositorySource}
              # Input artifacts do not apply for this action type (source).
              InputArtifacts: []
              # ZIP file that contains the contents of the configured repository and branch at the commit specified as the source revision 
              # for the pipeline execution. 
              OutputArtifacts:
                - Name: !Sub ${PipelineForApp}
              # Really it is not necessary because already get from resource property (RoleArn)
              #RoleArn: !Sub ${CodePipelineServiceRole}
          # Reserved for future use.
          #Blockers: 
            #- Name: String
              #Type: String

        # Deploy Stage 2: Code deployment on EC2
        - Name: 'Deploy-stage_Use_CodeDeploy_to_install_from_Ansible_playbooks'
          Actions:
            # Specifies the action type and the provider of the action.
            - Name: 'Deploy_Code_into_EC2_instances'
              RunOrder: 2
              Namespace: DeployNameSpace
              Region: !Sub ${RegionOfRepositorySource}
              ActionTypeId:
                # Valid categories are limited to one of the values below: Source,Build,Test,Deploy,Invoke,Approval.
                Category: Deploy
                # There are three valid values for the Owner field in the action category section within your pipeline structure:
                # AWS, ThirdParty, and Custom
                Owner: AWS
                # The provider of the service being called by the action. Valid providers are determined by the action category. 
                # For example, an action in the Deploy category type might have a provider of AWS CodeDeploy, which would be specified as CodeDeploy.
                # https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements
                Provider: CodeDeploy
                Version: !Sub ${VersionOfSource}
              # The action's configuration.
              Configuration:
                ApplicationName: !Sub ${CodeDeployApplicationName}
                # We recommend that you use CloudWatch Events to detect source changes instead.
                DeploymentGroupName: !Sub ${DeploymentGroupName}
              # The name of the application what this pipeline was created
              InputArtifacts:
                - Name: !Sub ${PipelineForApp}
              OutputArtifacts: []
      Tags:
        - Key: Name
          Value: !Sub '${AccountName}-${CodeDeployApplicationName}-pipeline'
        - Key: ApplicationName
          Value: !Sub '${CodeDeployApplicationName}'