---

##
# Alberto González Mesas, <alberto.gonzalez@euigs.com>
# Thur May 07 16:30:00 CEST 2020 
##

AWSTemplateFormatVersion: 2010-09-09

##############################################################################################
# Description                                                                                #
##############################################################################################

Description: >
  Create a new CodeDeploy Deployment Group. resource that defines deployment-related settings 
  like which instances to deploy to and how fast to deploy them.

##############################################################################################
# Metadata                                                                                   #
##############################################################################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Configure Environment.
        Parameters:
          - AccountName
      - Label:
          default: Configure Deployment Group Settings
        Parameters:
          - ApplicationName
          - DeploymentConfiguration
          - DeploymentGroupName
          - DeploymentType
          - DeploymentTrafficControl
          - RollbackEventType
          - AutomaticRollback
          - ServiceRoleArn
      - Label:
          default: Configure Tags Filters
        Parameters:
          - TagFilterType1 
          - CodeDeployTagKeyFilter1
          - CodeDeployTagValueFilter1
          - CodeDeployTagKeyFilter2
          - CodeDeployTagValueFilter2
          - CodeDeployTagKeyFilter3
          - CodeDeployTagValueFilter3
      - Label:
          default: Define SNS Topic Parameters
        Parameters:
          - snsEmailSubscriber
          - snsProto

##############################################################################################
# Parameters                                                                                 #
##############################################################################################

Parameters:
  AccountName:
    Description: 'The account name, ie euigs-dev-tlt'
    Type: String
    MinLength: 1
  ApplicationName:
    Description: >-
     'The name of an existing CodeDeploy application to associate this deployment group with.'
    Type: String
    MinLength: 1
  DeploymentConfiguration:
    Description: >-
      A deployment configuration name or a predefined configuration name.
    Type: String
    Default: CodeDeployDefault.OneAtATime
    AllowedValues:
      - CodeDeployDefault.OneAtATime
      - CodeDeployDefault.HalfAtATime
      - CodeDeployDefault.AllAtOnce
  DeploymentGroupName:
    Description: A name for the deployment group.
    Type: String
    MinLength: 1
  DeploymentType:
    Description: >-
      Indicates whether to run an in-place or blue/green deployment. Attributes that determine the type of deployment 
      to run and whether to route deployment traffic behind a load balancer. If you specify this property with a blue/green 
      deployment type, don't specify the AutoScalingGroups, LoadBalancerInfo, or Deployment properties.
    Type: String
    Default: IN_PLACE
    AllowedValues:
      - IN_PLACE
      - BLUE_GREEN
  DeploymentTrafficControl:
    Description: >-
      Indicates whether to route deployment traffic behind a load balancer.
    Type: String
    Default: WITHOUT_TRAFFIC_CONTROL
    AllowedValues:
      - WITHOUT_TRAFFIC_CONTROL
      - WITH_TRAFFIC_CONTROL
  RollbackEventType:
    Description: The event type or types that trigger a rollback.
    Type: String
    Default: DEPLOYMENT_FAILURE
    AllowedValues:
      - DEPLOYMENT_FAILURE
      - DEPLOYMENT_STOP_ON_ALARM
      - DEPLOYMENT_STOP_ON_REQUEST
  AutomaticRollback:
    Description: Indicates whether a defined automatic rollback configuration is currently enabled.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  ServiceRoleArn:
    Description: Select a valid Role. The role must have the AWSCodeDeployRole policy attached.
    Type: String
    Default: arn:aws:iam::691268106430:role/euigs-dev-tlt-CodeDeployForPipelines-role
  TagFilterType1:
    Description: The tag filter type.
    Type: String
    Default: 'KEY_AND_VALUE'
    AllowedValues:
      - KEY_AND_VALUE
      - KEY_ONLY
      - VALUE_ONLY
  CodeDeployTagKeyFilter1:
    Description: >-
      The EC2 tags that are already applied to EC2 instances that you want to include in the deployment group.
      CodeDeploy includes all EC2 instances identified by any of the tags you specify in this deployment group.
      Select a Key in order to match against EC2 tags.
    Type: String
  CodeDeployTagValueFilter1:
    Description: Select a value for Key 1.
    Type: String
  CodeDeployTagKeyFilter2:
    Description: Select a tag key 2.
    Type: String
  CodeDeployTagValueFilter2:
    Description: Select a value for Key 2.
    Type: String
  CodeDeployTagKeyFilter3:
    Description: Select a tag key 3.
    Type: String
  CodeDeployTagValueFilter3:
    Description: Select a value for Key 3.
    Type: String
  snsProto:
    Description: The subscription's protocol.
    Type: String
    MinLength: 1
    Default: 'email-json'
  snsEmailSubscriber:
    Description: The endpoint that receives notifications from the Amazon SNS topic.
    Type: String
    MinLength: 1
    Default: 'alberto.gonzalez@euigs.com'

##############################################################################################
# Resources                                                                                  #
##############################################################################################

Resources:
  SNSTopicEventNotification:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AccountName}-${ApplicationName}-cd-sns-topic'
      DisplayName: !Sub '${ApplicationName}'
      Subscription:
        - Endpoint: !Sub '${snsEmailSubscriber}'
          Protocol: !Sub '${snsProto}'
      Tags:
        - Key: Name
          Value: !Sub '${AccountName}-${ApplicationName}-sns'
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      # The Alarm property type specifies a CloudWatch alarm to use for an AWS CodeDeploy deployment group.
      # The Alarm property of the CodeDeploy DeploymentGroup AlarmConfiguration property contains a list of Alarm property types.
      # Information about the Amazon CloudWatch alarms that are associated with the deployment group.
      #AlarmConfiguration: 
        #Alarms:
          # The name of the alarm.
          #- Alarm1
          #- Alarm2
        #Enabled: False
        #IgnorePollAlarmFailure: true
      ApplicationName: !Sub ${ApplicationName}
      # Information about the automatic rollback configuration that is associated with the deployment group.
      # If you specify this property, don't specify the Deployment property.
      AutoRollbackConfiguration:
        Enabled: !Sub ${AutomaticRollback}
        Events: 
          - !Sub ${RollbackEventType}
      # A list of associated Auto Scaling groups that CodeDeploy automatically deploys revisions to when new
      # instances are created. Duplicates are not allowed.        
      #AutoScalingGroups:
         #- String
      # The application revision to deploy to this deployment group. If you specify this property, your target application
      # revision is deployed as soon as the provisioning process is complete. If you specify this property, don't specify
      # the AutoRollbackConfiguration property.
      #Deployment:
        # A comment about the deployment.
        #Description: String
        #IgnoreApplicationStopFailures: false
        # Information about the location of stored application artifacts and the service from which to retrieve them.
        #Revision: 
          #GitHubLocation: 
            #GitHubLocation
          # The type of application revision: AppSpecContent | GitHub | S3 | String
          #RevisionType: String
          #S3Location: 
            #S3Location
      DeploymentConfigName: !Sub ${DeploymentConfiguration}
      DeploymentGroupName: !Sub ${AccountName}-${DeploymentGroupName}
      DeploymentStyle:
        DeploymentOption: !Sub ${DeploymentTrafficControl}
        DeploymentType: !Sub ${DeploymentType}
      Ec2TagFilters:
        - Key: !Sub ${CodeDeployTagKeyFilter1}
          Type: !Sub ${TagFilterType1}
          Value: !Sub ${CodeDeployTagValueFilter1}
        - Key: !Sub ${CodeDeployTagKeyFilter2}
          Type: !Sub ${TagFilterType1}
          Value: !Sub ${CodeDeployTagValueFilter2}
        - Key: !Sub ${CodeDeployTagKeyFilter3}
          Type: !Sub ${TagFilterType1}
          Value: !Sub ${CodeDeployTagValueFilter3}
      # Information about groups of tags applied to EC2 instances. The deployment group includes only EC2 instances
      # identified by all the tag groups. Cannot be used in the same call as ec2TagFilter.
      #Ec2TagSet: 
        #EC2TagSet
      # Information about the load balancer to use in a deployment
      #LoadBalancerInfo:
        # An array that contains information about the load balancer to use for load balancing in a deployment.
        # If you specify the ELBInfo property, the DeploymentStyle.DeploymentOption property must be set to
        # WITH_TRAFFIC_CONTROL for AWS CodeDeploy to route your traffic using the specified load balancers.
        #ElbInfoList: 
          # For blue/green deployments, the name of the load balancer that is used to route traffic from original
          # instances to replacement instances in a blue/green deployment.
          # For in-place deployments, the name of the load balancer that instances are deregistered from so they
          # are not serving traffic during a deployment, and then re-registered with after the deployment is complete.
          #- Name: String
        # An array that contains information about the target group to use for load balancing in a deployment.
        #TargetGroupInfoList: 
          #- TargetGroupInfo
      #OnPremisesInstanceTagFilters: 
        #- TagFilter
      #OnPremisesTagSet: 
        #OnPremisesTagSet
      ServiceRoleArn: !Sub ${ServiceRoleArn}
      # Information about triggers associated with the deployment group. Duplicates are not allowed
      TriggerConfigurations: 
        # The event type or types that trigger notifications.
        - TriggerEvents: 
          - DeploymentStart
          - DeploymentSuccess
          - DeploymentRollback
          - DeploymentFailure
          - DeploymentStop
          # The name of the notification trigger.
          TriggerName: !Sub ${DeploymentGroupName}-eventsNotification
          # The ARN of the Amazon Simple Notification Service topic through which notifications about deployment 
          # or instance events are sent.
          TriggerTargetArn: !Ref SNSTopicEventNotification