---

##
# Alberto González Mesas, <alberto.gonzalez@euigs.com>
# Mon Apr 29 16:30:00 CEST 2020 
##

AWSTemplateFormatVersion: 2010-09-09

##############################################################################################
# Description                                                                                   #
##############################################################################################

Description: >
  Create a new CodeDeploy Application.

##############################################################################################
# Metadata                                                                                   #
##############################################################################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Create a CodeCommit repository.
        Parameters:
          - AccountName
          - ApplicationName
          - ComputePlatform

##############################################################################################
# Parameters                                                                                 #
##############################################################################################

Parameters:
  AccountName:
    Description: 'The account name, ie euigs-dev-tlt'
    Type: String
    MinLength: 1
  ApplicationName:
    Description: >-
     'The CodeDeploy Application name, ie ApacheHardening.'
    Type: String
    MinLength: 1
  ComputePlatform:
    Description: 'The compute platform that CodeDeploy deploys the application to.'
    Type: String
    Default: Server
    AllowedValues:
      - ECS
      - Lambda
      - Server

##############################################################################################
# Resources                                                                                  #
##############################################################################################

Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: !Sub '${AccountName}-${ApplicationName}-cd'
      ComputePlatform: !Sub '${ComputePlatform}'
