---
# Main role to install and configure HAproxy service.

- name: Install HA-Proxy service.
  apt:
    name: haproxy
    allow_unauthenticated: no
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time|default(3600) }}"
    state: present
    install_recommends: yes
  environment:
    RUNLEVEL: 1

  # Configure Systemd Service.
- include_tasks: utils/systemd.yml 
  vars:
    service: '{{ haproxy_service }}'
  tags: systemd

- name: Configure HA-Proxy service.
  template: 
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg