AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This AWS CloudFormation template creates an Amazon EC2 instance based on an
  AMI, an Elastic File System, an Application Load Balancer and an Auto Scaling
  Group. You will be billed for the AWS resources used if you create a stack
  from this template.
Parameters:
  # Ownership
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: FirstName LastName
  Project:
    Type: String
    Default: MySQL RDS Creation
  DeleteAfter:
    Description: Enter Date It's Ok to Delete the Stack or 'Never' if meant to be persistent.
    Type: String
    Default: 00/00/201x
  AccountName:
    Type: String
    Description: A prefix to tag the generated resources
    MinLength: 1
  ApplicationName:
    Type: String
    Description: The name of the application to tag the generated resources
    MinLength: 1

  # Network
  VPC:
    Description: Select VPC.
    Type: AWS::EC2::VPC::Id
  TcpPort:
    Description: Enter RDS Listening TCP Port number.
    Type: Number
    Default: 5432

  # Backup Settings
  BackupRetentionPeriod:
    Description: Enter Backup Retention Period in Days.
    Type: Number
    Default: 7
  PreferredBackupWindow:
    Description: Enter Preferred Backup Window Time (UTC).
    Type: String
    Default: 17:00-19:00
  PreferredMaintenanceWindow:
    Description: Enter Preferred Maintenance Window Time (UTC).
    Type: String
    Default: Sun:19:00-Sun:23:00

  # Patching
  AutoMinorVersionUpgrade:
    Description: Allow Automatic Minor Version Upgrades?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'

  # Hardware
  InstanceType:
    Type: String
    Default: db.t2.micro
    AllowedValues:
    - db.t1.micro
    - db.t2.micro
    - db.t2.small
    - db.t2.medium
    - db.t2.large
    - db.m1.small
    - db.m1.medium
    - db.m1.large
    - db.m1.xlarge
    - db.m3.medium
    - db.m3.large
    - db.m3.xlarge
    - db.m3.2xlarge
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m4.4xlarge
    - db.m4.10xlarge
    - db.r3.large
    - db.r3.xlarge
    - db.r3.2xlarge
    - db.r3.4xlarge
    - db.r3.8xlarge
  MultiAvailabilityZone:
    Description: Enable Multi Availability Zones?
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'

  # Engine
  Engine:
    Type: String
    Default: mysql
    AllowedValues:
    - aurora
    - aurora-mysql
    - aurora-postgresql
    - mariadb
    - mysql
    - oracle-ee
    - oracle-se2
    - oracle-se1
    - oracle-se
    - postgres
    - sqlserver-ee
    - sqlserver-se
    - sqlserver-ex
    - sqlserver-web
  EngineVersion:
    Type: String
    Default: '10.6'
    AllowedValues:
    - '11.4'
    - '11.2'
    - '11.1'
    - '10.9'
    - '10.7'
    - '10.6'
    - '5.7.26'
    - '5.7.25'
    - '5.7.24'
    - '5.7.23'
    - '5.7.22'
    - '5.6.44'
    - '5.6.43'
    - '5.6.41'
    - '5.6.40'

  # Restore
  DBName:
    Description: 'Name of the database (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: String
    Default: ''
  DBSnapshotIdentifier:
    Description: 'Optional name or Amazon Resource Name (ARN) of the DB snapshot from which you want to restore (leave blank to create an empty database).'
    Type: String
    Default: ''   
  DBInstanceIdentifier:
    Description: 'Name for the DB instance needed for the endpoint. Leave blank if restoring from snapshot'
    Type: String
    Default: ''
  MasterUsername:
    Description: 'If a new database is created, provide the master username'
    Type: String
    Default: ''
  DBSecurityGroup:
    Description: 'Security Group ID assigned to the DB instance'
    Type: String
    Default: ''
  
  RDSSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for RDS
    ConstraintDescription: >-
      must be a list of two existing RDS subnets associated with two different
      availability zones. They should be residing in the selected Virtual Private
      Cloud.
Conditions:
  UseDBSnapshot: !Not [!Equals [!Ref DBSnapshotIdentifier, '']]

Resources:
    DbInstance:
        Type: AWS::RDS::DBInstance
        DeletionPolicy: Delete
        Properties:
          AllocatedStorage : '20'
          DBSnapshotIdentifier: !If [UseDBSnapshot, !Ref DBSnapshotIdentifier, !Ref "AWS::NoValue"]
          DBInstanceIdentifier: !Ref DBInstanceIdentifier
          DBName: !If [UseDBSnapshot, !Ref "AWS::NoValue", !Ref DBName]
          MasterUsername : !If [UseDBSnapshot, !Ref "AWS::NoValue", !Ref MasterUsername]
          MasterUserPassword : '{{resolve:ssm-secure:/Applications/EUIGS/SecurityMonkey/RDS/PostgreSQL/password:1}}'
          AllowMajorVersionUpgrade: false
          AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
          BackupRetentionPeriod: !Ref BackupRetentionPeriod
          DBInstanceClass: !Ref InstanceType
          DBSubnetGroupName : !Ref DBSubnetGroup
          Engine : !Ref Engine
          EngineVersion : !Ref EngineVersion
          MultiAZ: !Ref MultiAvailabilityZone
          Port: !Ref TcpPort
          PreferredBackupWindow: !Ref PreferredBackupWindow
          PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
          PubliclyAccessible: false
          StorageEncrypted: true
          StorageType: gp2
          DeleteAutomatedBackups: true
          VPCSecurityGroups: 
          - !Ref DBSecurityGroup
          Tags:
            - Key: ApplicationID
              Value: !Sub ${ApplicationName}
            - Key: Name
              Value: !Sub ${AccountName}-${ApplicationName}-rds
            - Key: CECO
              Value: shared
            - Key: Compliance
              Value: yes
            - Key: Confidentiality
              Value: yes
            - Key: EndTime
              Value: 0
            - Key: Environment
              Value: prod
            - Key: Operation
              Value: euigs
            - Key: Role
              Value: services
            - Key: SLA
              Value: 24x7
            - Key: StartTime
              Value: 0
    DBSubnetGroup: 
        Type : 'AWS::RDS::DBSubnetGroup'
        Properties: 
            DBSubnetGroupDescription: 'DBSubnetGroup for RDS used by security monkey'
            DBSubnetGroupName: 'db-secmonkey-subnet-group'
            SubnetIds: !Ref RDSSubnets