AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This AWS CloudFormation template creates an Amazon EC2 instance based on an
  AMI, an Elastic File System, an Application Load Balancer and an Auto Scaling
  Group. You will be billed for the AWS resources used if you create a stack
  from this template.
Parameters:
  # Ownership
  AccountName:
    Type: String
    Description: A prefix to tag the generated resources
    MinLength: 1
  ApplicationName:
    Type: String
    Description: The name of the application to tag the generated resources
    MinLength: 1

  # Network
  VPC:
    Description: Select VPC.
    Type: AWS::EC2::VPC::Id
  TcpPort:
    Description: Enter RDS Listening TCP Port number.
    Type: Number
    Default: 5432

  # Backup Settings
  BackupRetentionPeriod:
    Description: Enter Backup Retention Period in Days.
    Type: Number
    Default: 7
  PreferredBackupWindow:
    Description: Enter Preferred Backup Window Time (UTC).
    Type: String
    Default: 17:00-19:00
  PreferredMaintenanceWindow:
    Description: Enter Preferred Maintenance Window Time (UTC).
    Type: String
    Default: Sun:19:00-Sun:23:00

  # Patching
  AutoMinorVersionUpgrade:
    Description: Allow Automatic Minor Version Upgrades?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'

  # Hardware
  InstanceType:
    Type: String
    Default: db.t2.medium
    AllowedValues:
    - db.t1.micro
    - db.t2.micro
    - db.t2.small
    - db.t2.medium
    - db.t2.large
    - db.m1.small
    - db.m1.medium
    - db.m1.large
    - db.m1.xlarge
    - db.m3.medium
    - db.m3.large
    - db.m3.xlarge
    - db.m3.2xlarge
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m4.4xlarge
    - db.m4.10xlarge
    - db.m5.xlarge
    - db.r3.large
    - db.r3.xlarge
    - db.r3.2xlarge
    - db.r3.4xlarge
    - db.r3.8xlarge
  MultiAvailabilityZone:
    Description: Enable Multi Availability Zones?
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'

  # Engine
  Engine:
    Type: String
    Default: mysql
    AllowedValues:
    - aurora
    - aurora-mysql
    - aurora-postgresql
    - mariadb
    - mysql
    - oracle-ee
    - oracle-se2
    - oracle-se1
    - oracle-se
    - postgres
    - sqlserver-ee
    - sqlserver-se
    - sqlserver-ex
    - sqlserver-web
  EngineVersion:
    Type: String
    Default: '5.7.26'
    AllowedValues:
    - '11.4'
    - '11.2'
    - '11.1'
    - '10.9'
    - '10.7'
    - '10.6'
    - '5.7.26'
    - '5.7.25'
    - '5.7.24'
    - '5.7.23'
    - '5.7.22'
    - '5.6.44'
    - '5.6.43'
    - '5.6.41'
    - '5.6.40'
    - '8.0.11'
    - '14.00.3223.3.v1'

  # Restore
  DBName:
    Description: 'Name of the database (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: String
    Default: ''
  DBSnapshotIdentifier:
    Description: 'Optional name or Amazon Resource Name (ARN) of the DB snapshot from which you want to restore (leave blank to create an empty database).'
    Type: String
    Default: ''
  DBSecurityGroup:
    Description: 'Security Group ID assigned to the DB instance.'
    Type: String
    Default: ''
  
  RDSSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for RDS. Choose at least 2.
    ConstraintDescription: >-
      must be a list of two existing RDS subnets associated with two different
      availability zones. They should be residing in the selected Virtual Private
      Cloud.

  # Accessibility
  Encryption:
    Description: Is the DDBB instance encrypted?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  PublicAccessibility:
    Description: Is the DDBB instance publicly accessible?
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'    

  # Tags
  CECO:
    Description: 'Center cost / business unit this resource is deployed for'
    Type: String
    Default: 'shared'
    AllowedValues:
    - 'ef'
    - 'ct'
    - 'as'
    - 'shared'
    - 'security'
    - 'dev'
  Compliance:
    Description: 'This resource is affected by regulations. In case it is not, use no'
    Type: String
    Default: ''
  Confidentiality:
    Description: 'This resource stores sensible data'
    Type: String
    Default: ''
  EndTime:
    Description: 'For SLA=8x5, hour at which a resource should be stopped/terminated. In case using 24x7, then StartTime and EndTime must be 00:00'
    Type: String
    Default: ''
  StartTime:
    Description: 'For SLA=8x5, hour at which a resource should be started. In case using 24x7, then StartTime and EndTime must be 00:00'
    Type: String
    Default: ''
  Environment:
    Description: 'Name of environment'
    Type: String
    Default: ''
  Operation:
    Description: 'Admiral operation accountable for this resource'
    Type: String
    Default: 'euigs'
    AllowedValues:
    - 'ef'
    - 'ct'
    - 'as'
    - 'euigs'
  Role:
    Description: 'Identifies a domain within an application'
    Type: String
    Default: 'services'
    AllowedValues:
    - 'web'
    - 'services'
    - 'middleware'
    - 'backend'
  SLA:
    Description: 'Identify non-stoppable resources. In case it is infrastructure, set it as 0'
    Type: String
    Default: '24x7'
    AllowedValues:
    - '8x5'
    - '24x7'
  DBSubnetGroupDescription:
    Description: 'Description of the subnet group. In must include the name of the project'
    Type: String
    Default: ''  
Conditions:
  UseDBSnapshot: !Not [!Equals [!Ref DBSnapshotIdentifier, '']]

Resources:
  DbInstance:
      Type: AWS::RDS::DBInstance
      DeletionPolicy: Delete
      Properties:
        AllocatedStorage : '20'
        DBSnapshotIdentifier: !If [UseDBSnapshot, !Ref DBSnapshotIdentifier, !Ref "AWS::NoValue"]
        DBName: !If [UseDBSnapshot, !Ref "AWS::NoValue", !Ref DBName]
        MasterUsername : !If [UseDBSnapshot, !Ref "AWS::NoValue", '{{resolve:ssm:/Applications/CT/Claims/RDS/SQLServer/Dev2/username:1}}']
        MasterUserPassword : !If [UseDBSnapshot, !Ref "AWS::NoValue", '{{resolve:ssm:/Applications/CT/Claims/RDS/SQLServer/Dev2/password:1}}']
        AllowMajorVersionUpgrade: false
        AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
        BackupRetentionPeriod: !Ref BackupRetentionPeriod
        DBInstanceClass: !Ref InstanceType
        DBSubnetGroupName : !Ref DBSubnetGroup
        LicenseModel: license-included
        Engine : !Ref Engine
        EngineVersion : !Ref EngineVersion
        MultiAZ: !Ref MultiAvailabilityZone
        Port: !Ref TcpPort
        PreferredBackupWindow: !Ref PreferredBackupWindow
        PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
        PubliclyAccessible: !Ref PublicAccessibility
        StorageEncrypted: !Ref Encryption
        StorageType: gp2
        DeleteAutomatedBackups: true
        EnableCloudwatchLogsExports: 
          - agent
          - error
        VPCSecurityGroups: 
          - !Ref DBSecurityGroup
        Tags:
          - Key: ApplicationID
            Value: !Sub ${ApplicationName}
          - Key: Name
            Value: !Sub ${AccountName}-${ApplicationName}-rds
          - Key: CECO
            Value: !Sub ${CECO}
          - Key: Compliance
            Value: !Sub ${Compliance}
          - Key: Confidentiality
            Value: !Sub ${Confidentiality}
          - Key: EndTime
            Value: !Sub ${EndTime}
          - Key: Environment
            Value: !Sub ${Environment}
          - Key: Operation
            Value: !Sub ${Operation}
          - Key: Role
            Value: !Sub ${Role}
          - Key: SLA
            Value: !Sub ${SLA}
          - Key: StartTime
            Value: !Sub ${StartTime}
  DBSubnetGroup: 
      Type : 'AWS::RDS::DBSubnetGroup'
      Properties: 
          DBSubnetGroupDescription:  !Sub ${DBSubnetGroupDescription}
          DBSubnetGroupName: !Sub ${AccountName}-${ApplicationName}-rds-subnet-group
          SubnetIds: !Ref RDSSubnets
  ReplicaDB:
    Type: AWS::RDS::DBInstance
    Properties:
      SourceDBInstanceIdentifier: !Ref 'DbInstance'
      DBInstanceClass: !Ref InstanceType
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      MultiAZ: !Ref MultiAvailabilityZone
      PubliclyAccessible: !Ref PublicAccessibility
      StorageEncrypted: !Ref Encryption
      StorageType: gp2
      DeleteAutomatedBackups: true
      VPCSecurityGroups: 
        - !Ref DBSecurityGroup
      Tags:
        - Key: ApplicationID
          Value: !Sub ${ApplicationName}
        - Key: Name
          Value: !Sub ${AccountName}-${ApplicationName}-readreplica-rds
        - Key: CECO
          Value: !Sub ${CECO}
        - Key: Compliance
          Value: !Sub ${Compliance}
        - Key: Confidentiality
          Value: !Sub ${Confidentiality}
        - Key: EndTime
          Value: !Sub ${EndTime}
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Operation
          Value: !Sub ${Operation}
        - Key: Role
          Value: !Sub ${Role}
        - Key: SLA
          Value: !Sub ${SLA}
        - Key: StartTime
          Value: !Sub ${StartTime}