#!/bin/sh -e

#
# This script is executed in the post-removal phase
#
#   On Debian/Ubuntu
#       $1=remove    : indicates a removal
#       $1=purge     : indicates a removal --purge
#
# You must just use this script to delete user and group. Also,
# delete any not empty directories.

# Sets the default values for pydeb variables used in this script
pydeb_user="pydeb"
pydeb_group="pydeb"

OURCE_ENV_FILE=true
REMOVE_DIRS=false
REMOVE_USER_AND_GROUP=false

case $1 in
  # Includes cases for all valid arguments, exit 1 otherwise
  # Debian
  remove)
    REMOVE_USER_AND_GROUP=true
    REMOVE_DIRS=false
  ;;
  purge)
    REMOVE_DIRS=true
  ;;
  failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|disappear)
  ;;
  *)
      echo "post remove script called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

if [ "$REMOVE_USER_AND_GROUP" = "true" ]; then
  echo "Deleting $pydeb_user user..."

  if getent passwd "$pydeb_user" >/dev/null; then
    userdel -r "$pydeb_user"
  fi
fi

# if [ "$REMOVE_DIRS" = "true" ]; then
#   if [ -d "$pydeb_home" ]; then
#     echo -e "Removing pydeb directories..."
#     rm -rf $pydeb_home && echo "... OK"
#   fi

#   if [ -d "$pydeb_tmp" ]; then
#     echo -e "Deleting $pydeb_tmp directory..."
#     rm -rf $pydeb_tmp && echo "... OK"
#   fi
# fi

exit 0
