#!/bin/bash -e

#
# This script is executed in the pre-remove phase
#
#   On Debian/Ubuntu
#       $1=remove    : indicates a removal
#       $1=purge     : indicates a removal --purge
#       $1=upgrade   : indicates an upgrade
#
# You must just use this script to stop the service and delete any directory or file
# that it not exists in package hierarchy standar.

STOP_REQUIRED=false
REMOVE_SERVICE=false

case "$1" in

    # Debian ####################################################
    remove|purge)
        STOP_REQUIRED=true
        REMOVE_SERVICE=true
    ;;
    upgrade)
        if [ "$RESTART_ON_UPGRADE" = "true" ]; then
            STOP_REQUIRED=true
        fi
    ;;
    deconfigure|failed-upgrade)
    ;;
    *)
        echo "pre remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Stops the service
if [ "$STOP_REQUIRED" = "true" ]; then
    echo -e "Stopping pydeb services..."
    if command -v systemctl >/dev/null; then
	if systemctl is-active pydeb.service >/dev/null; then
        	systemctl --no-reload stop pydeb.service
	fi
    fi
    echo "... OK"
fi

if [ "$REMOVE_SERVICE" = "true" ]; then
    if command -v systemctl >/dev/null; then
	if systemctl is-active pydeb.service >/dev/null; then
	        systemctl disable pydeb.service > /dev/null 2>&1
        fi
    fi
fi

# EXAMPLES: DELETE SYMLINKS AND DIRECTORIES
 #    if [ ${pydeb_symlink} ]; then
 #       	echo -e "Removing ${pydeb_symlink}"
	# rm ${SYMLINK_HARDRELOAD} && echo -e "... OK"
 #    fi

 #    if [ ${pydeb_tmp_dir} ]; then
	# echo -e "Removing ${pydeb_tmp_dir}"
	# rm ${pydeb_tmp_dir} && echo -e "... OK"
 #    fi

exit 0
