---

##
# Alberto González Mesas, <alberto.gonzalez@euigs.com>
# lun sep 18 12:47:00 CEST 2019
##

AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates an encrypted S3 bucket, with denied public access, enabled MFA for
  deletion, tagging and activated versioning.

##############################################################################################
# Metadata                                                                                   #
##############################################################################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Setup account configuration.
        Parameters:
          - AccountName
      - Label:
          default: Configure S3 Bucket.
        Parameters:
          - S3BucketName
          - S3EncryptionProto
          - S3PublicAccess
          - S3DeletionPolicy
          - S3EnableVersioning
      - Label:
          default: Tagging
        Parameters:
          - Role
          - Environment
          - SLA
          - StartTime
          - EndTime
          - CECO
          - Operation
          - Compliance
          - Confidentiality
      - Label:
          default: Lifecycle configuration.
        Parameters:
          - S3Lifecycle
          - S3NumDaysAbortIncompleteMultipartUpload
          - S3NumDaysFirstTransitionsCurrentObject
          - S3FirstTransitionsCurrentObjectStorageClass
          - S3NumDaysSecondTransitionsCurrentObject
          - S3SecondTransitionsCurrentObjectStorageClass
          - S3FullExpirationCurrentObjectInDays
          - S3NumDaysFirstTransitionsNonCurrentObject
          - S3FirstTransitionsNonCurrentObjectStorageClass
          - S3NumDaysSecondTransitionsNonCurrentObject
          - S3SecondTransitionsNonCurrentObjectStorageClass
          - S3FullExpirationNonCurrentObjectInDays
    ParameterLabels:
      AccountName:
        default: Account Name

##############################################################################################
# Parameters                                                                                 #
##############################################################################################

Parameters:
  AccountName:
    Type: String
    Description: 'The account name, ie ''euigs-dev-base'''
    MinLength: 1
  S3BucketName:
    Type: String
    Description: >-
      Indicates the name for S3 bucket. The name will finally be
      AccountName-S3BucketName.
    MinLength: 1
  S3EncryptionProto:
    Type: String
    Description: Indicates the encryption protocol. Set to 'AES256' by default.
    Default: AES256
    AllowedValues:
      - 'aws:kms'
      - AES256
  S3PublicAccess:
    Type: String
    Description: |
      Enable/Deny the public access.
        'PublicReadWrite' full public access,
        'PublicRead' to hold website content,
        'Private' deny the public access,
        'LogDeliveryWrite' for only log registry
      Default value is Private.
    Default: Private
    AllowedValues:
      - PublicReadWrite
      - PublicRead
      - Private
      - LogDeliveryWrite
  S3DeletionPolicy:
    Type: String
    Description: Deletion Policy set to 'Delete' (hardcoded).
    Default: Delete
    AllowedValues:
      - Delete
      - Retain
      - Snapshot
  S3EnableVersioning:
    Type: String
    Description: Enable S3 Bucket data versioning. Unversioned by the default.
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
  Role:
    Type: String
    Description: 'Tag: Role of resource.'
    Default: dev
    AllowedValues:
      - dev
      - staging
      - pro
  Environment:
    Type: String
    Description: 'Tag: Environment where the resource is spawned.'
    Default: dev
    AllowedValues:
      - dev
      - int
      - pro
  SLA:
    Type: String
    Description: 'Tag: Service-level agreement.'
    Default: 24x7
    AllowedValues:
      - '24x7'
      - '8x5'
  StartTime:
    Type: String
    Description: 'When is the resource spawned?, ie ''00:00''.'
    Default: '00:00'
  EndTime:
    Type: String
    Description: 'When is the resource terminated?, ie ''18:30''.'
    Default: '00:00'
  CECO:
    Type: String
    Description: 'Operation owner of resource deployed, ie ''the same as Operation tag''.'
    Default: euigs
  Operation:
    Type: String
    Description: 'Operation owner of resource deployed.'
    Default: euigs
    AllowedValues:
      - euigs
      - as
      - ct 
      - ef
  Compliance:
    Type: String
    Description: Compliance.
    Default: 'no'
    AllowedValues:
      - 'no'
      - 'yes'
  Confidentiality:
    Type: String
    Description: Confidentiality.
    Default: 'no'
    AllowedValues:
      - 'yes'
      - 'no'
  S3Lifecycle:
    Type: String
    Description: Enable Global objects Lifecycle (log files are not include).
    Default: Disabled
    AllowedValues:
      - Enabled
      - Disabled
  S3NumDaysAbortIncompleteMultipartUpload:
    Type: Number
    Description: >-
      Specifies the days since the initiation of an incomplete multipart upload that Amazon S3 will 
      wait before permanently removing all parts of the upload. 
    Default: 7
  S3NumDaysFirstTransitionsCurrentObject:
    Type: Number
    Description: >-
      Indicates the number of days after creation when objects are transitioned to the specified storage 
      class. The value must be a positive integer.
    Default: 90
  S3FirstTransitionsCurrentObjectStorageClass:
    Type: String
    Description: The storage class to which you want the current object to transition.
    Default: STANDARD_IA
    AllowedValues:
      - STANDARD_IA
      - ONEZONE_IA
      - INTELLIGENT_TIERING
      - GLACIER
      - DEEP_ARCHIVE
  S3NumDaysSecondTransitionsCurrentObject:
    Type: Number
    Description: >-
      Indicates the number of days to spend in 'S3FirstTransitionsCurrentObjectStorageClass' before the object are transitioned to 
      'S3SecondTransitionsCurrentObjectStorageClass'. The value must be a positive integer.
    Default: 180
  S3SecondTransitionsCurrentObjectStorageClass:
    Type: String
    Description: The storage class to which you want the current object to second transition.
    Default: GLACIER
    AllowedValues:
      - STANDARD_IA
      - ONEZONE_IA
      - INTELLIGENT_TIERING
      - GLACIER
      - DEEP_ARCHIVE
  S3FullExpirationCurrentObjectInDays:
    Type: Number
    Description: Indicates when objects are deleted from Amazon S3 and Amazon S3 Glacier.
    Default: 360
  S3NumDaysFirstTransitionsNonCurrentObject:
    Type: Number
    Description: >-
      Indicates the number of days after the object was marked for deletion when NON-current objects are transitioned to 
      the specified storage class. The value must be a positive integer.
    Default: 90
  S3FirstTransitionsNonCurrentObjectStorageClass:
    Type: String
    Description: The storage class to which you want the NON-current object to transition.
    Default: STANDARD_IA
    AllowedValues:
      - STANDARD_IA
      - ONEZONE_IA
      - INTELLIGENT_TIERING
      - GLACIER
      - DEEP_ARCHIVE
  S3NumDaysSecondTransitionsNonCurrentObject:
    Type: Number
    Description: >-
      Indicates the number of days to spend in 'S3FirstTransitionsNonCurrentObjectStorageClass' before the object are transitioned to 
      'S3SecondTransitionsNonCurrentObjectStorageClass'. The value must be a positive integer.
    Default: 180
  S3SecondTransitionsNonCurrentObjectStorageClass:
    Type: String
    Description: The storage class to which you want the NON-current object to second transition.
    Default: GLACIER
    AllowedValues:
      - STANDARD_IA
      - ONEZONE_IA
      - INTELLIGENT_TIERING
      - GLACIER
      - DEEP_ARCHIVE
  S3FullExpirationNonCurrentObjectInDays:
    Type: Number
    Description: >-
      For buckets with versioning enabled (or suspended), specifies the time, in days, between when a new version of 
      the object is uploaded to the bucket and when old versions of the object expire.
    Default: 360

##############################################################################################
# Conditions                                                                                 #
##############################################################################################

Conditions:
  isNotPublicAccess: !Equals [!Ref S3PublicAccess, Private]
  isWebSite: !Equals [!Ref S3PublicAccess, PublicRead]

##############################################################################################
# Resources                                                                                  #
##############################################################################################

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${AccountName}-${S3BucketName}-s3'
      AccessControl: !Sub '${S3PublicAccess}'
      WebsiteConfiguration:
        !If [isWebSite,
              [
                IndexDocument: index.html, 
                ErrorDocument: error.html
              ], 
              !Ref "AWS::NoValue"
            ]
      VersioningConfiguration:
        Status: !Sub '${S3EnableVersioning}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Sub '${S3EncryptionProto}'
      LifecycleConfiguration:
        Rules:
          # 1. Transition objetcs (current and previous) from STANDARD Storage to STANDARD_IA 90 days after they are created.
          # 2. Transition objetcs (current and previous) from STANDARD_IA Storage to GLACIER 180 days after they are created.
          # 3. Amazon S3 removes (current and previous) 90 days after they are created by adding a delete marker.
          # Lifecycle total duration: 360 days
          - Id: Remove objetcs after 360 days
            Status: !Sub '${S3Lifecycle}'
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: !Sub ${S3NumDaysAbortIncompleteMultipartUpload}
            # Transition objects from one storage class to another (applies to the current object version)
            Transitions:
              - StorageClass: !Sub ${S3FirstTransitionsCurrentObjectStorageClass}
                TransitionInDays: !Sub ${S3NumDaysFirstTransitionsCurrentObject}
              - StorageClass: !Sub ${S3SecondTransitionsCurrentObjectStorageClass}
                TransitionInDays: !Sub ${S3NumDaysSecondTransitionsCurrentObject}
            # The expiration time must be later than the transition time. Set object to noncurrent.
            ExpirationInDays: !Sub ${S3FullExpirationCurrentObjectInDays}
            # Transition objects from one storage class to another (applies to the noncurrent object version)
            NoncurrentVersionTransitions:
              - StorageClass: !Sub ${S3FirstTransitionsNonCurrentObjectStorageClass}
                TransitionInDays: !Sub ${S3NumDaysFirstTransitionsNonCurrentObject}
              - StorageClass: !Sub ${S3SecondTransitionsNonCurrentObjectStorageClass}
                TransitionInDays: !Sub ${S3NumDaysSecondTransitionsNonCurrentObject}
            # Amazon S3 permanently removes these object versions
            NoncurrentVersionExpirationInDays: !Sub ${S3FullExpirationNonCurrentObjectInDays}
      PublicAccessBlockConfiguration:
        !If
          - isNotPublicAccess
          -
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          -
            BlockPublicAcls: false
            BlockPublicPolicy: false
            IgnorePublicAcls: false
            RestrictPublicBuckets: false
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Sub '${AccountName}-${S3BucketName}-s3'