---
kafka_fresh_install: true
# Connexion
kafka_broker_port: 9092
kafka_broker: "{% if kafka_id|default(0) >= 1 %}kafka{{ kafka_id }}{%else%}{{ ansible_hostname }}{%endif%}"

# server.properties.j2
broker_id_generation_enable: 'true'
reserved_broker_max_id: 9
auto_create_topics_enable: 'false'
delete_topic_enable: 'true'
controlled_shutdown_enable: 'true'
controlled_shutdown_max_retries: 3
controlled_shutdown_retry_backoff_ms: 5000
auto_leader_rebalance_enable: 'true'
leader_imbalance_check_interval_seconds: 300
leader_imbalance_per_broker_percentage: 10
controller_socket_timeout_ms: 30000
num_network_threads: 3
num_io_threads: 8
background_threads: 10
socket_send_buffer_bytes: 102400
socket_receive_buffer_bytes: 102400
socket_request_max_bytes: 104857600
queued_max_requests: 500
message_max_bytes: 1000012
ahead_log_dirs: "{{ kafka_store }}"
num_partitions: 1
num_recovery_threads_per_data_dir: 1
offsets_topic_replication_factor: 1
transaction_state_log_replication_factor: 1
transaction_state_log_min_isr: 1
default_replication_factor: 1
log_flush_interval_messages: 20000
log_flush_interval_ms: 300000
log_flush_scheduler_interval_ms: 60000
log_flush_offset_checkpoint_interval_ms: 60000
log_retention_hours: 1
log_retention_bytes: -1
log_segment_bytes: 536870912
log_roll_hours: 1
log_retention_check_interval_ms: 30000
log_cleanup_policy: 'delete'
log_cleaner_enable: 'true'
log_cleaner_threads: 1
log_cleaner_dedupe_buffer_size: 134217728
log_cleaner_io_buffer_size: 524288
log_index_size_max_bytes: 10485760
log_index_interval_bytes: 4096
log_delete_delay_ms: 60000
log_segment_delete_delay_ms: 6000
zookeeper_session_timeout_ms: 6000
zookeeper_sync_time_ms: 2000
zookeeper_connection_timeout_ms: 12000
delete_records_purgatory_purge_interval_requests: 1
fetch_purgatory_purge_interval_requests: 100
producer_purgatory_purge_interval_requests: 100