---
cerebro_service: 'cerebro'
cerebro_user: 'cerebro'
cerebro_group: 'cerebro'
cerebro_base: '/opt/cerebro'
cerebro_conf_dir: '{{ cerebro_base }}/conf'
cerebro_conf_file: '{{ cerebro_conf_dir }}/application.conf'
cerebro_log4j_file: '{{ cerebro_conf_dir }}/logback.xml'
cerebro_reference_file: '{{ cerebro_conf_dir }}/reference.conf'
cerebro_pid_dir: '/var/run/cerebro'
cerebro_pid_file: '{{ cerebro_pid_dir }}/cerebro.pid'
cerebro_database_path: '/opt/cerebro/data/cerebro.db'
cerebro_log_dir: '/var/log/cerebro'
cerebro_log_file: '{{ cerebro_log_dir }}/cerebro.log'