---
- name: daemon reload
  systemd: 
    daemon_reload: yes

- name: start {{ haproxy_service }}
  systemd:
    name: '{{ haproxy_service }}'
    state: started
    enabled: yes

- name: restart {{ haproxy_service }}
  systemd:
    name: '{{ haproxy_service }}'
    state: restarted

- name: stop {{ haproxy_service }}
  systemd:
    name: '{{ haproxy_service }}'
    state: stopped

- name: reload {{ haproxy_service }}
  systemd:
    name: '{{ haproxy_service }}'
    state: reloaded