---
- name: daemon reload
  systemd: 
    daemon_reload: yes

- name: start {{ redis_service }}
  systemd:
    name: '{{ redis_service }}'
    state: started
    enabled: yes

- name: restart {{ redis_service }}
  systemd:
    name: '{{ redis_service }}'
    state: restarted

- name: stop {{ redis_service }}
  systemd:
    name: '{{ redis_service }}'
    state: stopped

- name: reload {{ redis_service }}
  systemd:
    name: '{{ redis_service }}'
    state: reloaded