---
- name: Install Logstash service.
  apt:
    name: logstash
    allow_unauthenticated: no
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time|default(3600) }}"
    state: present
    install_recommends: yes
  environment:
    RUNLEVEL: 1

- name: Configure Logstash service.
  template: 
    src: '{{ item }}.j2'
    dest: "{{ logstash_conf_dir }}/{{ item }}"
  with_items:
    - FILTER-TIMESTAMP.conf
    - INPUT-KAFKA.conf
    - OUTPUT-ES.conf

- name: Configure Logstash init.d.
  template:
    src: logstash.j2
    dest: '/etc/init.d/logstash'

- name: Configure Logstash Defaults.
  template:
    src: logstash-default.j2
    dest: '/etc/default/logstash'

