---

##
# Alberto González Mesas, <a.gonzalezmesasz@gmail.com>
# Tue Ene 14 10:30:00 CEST 2020 
##

AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploy a new compliance EC2 instance.

##############################################################################################
# Metadata                                                                                   #
##############################################################################################

Metadata:
  AWS::CloudFormation::Interface:

    ParameterGroups:
      - Label:
          default: Set up account configuration.
        Parameters:
          - AccountName
          - EnvType
          - RoleName
          - ARNPolicy

      - Label:
          default: Tagging
        Parameters:
          - TagRole
          - TagEnvironment
          - TagSLA
          - TagStartTime
          - TagEndTime
          - TagCECO
          - TagOperation
          - TagCompliance
          - TagConfidentiality

    ParameterLabels:
      AccountName:
        default: Account Name
      EnvType:
        default: Deployment environment
      RoleName:
        default: Role Name
      ARNPolicy:
        default: ARN Policy

##############################################################################################
# Parameters                                                                                 #
##############################################################################################

Parameters:
  AccountName:
    Description: 'The account name'
    Type: String
    MinLength: 1
  EnvType: 
    Description: 'Environment where the App will be deployed.'
    Type: String
    Default: development
    AllowedValues: 
      - development
      - integration
      - production
  RoleName:
    Description: 'The Role name'
    Type: String
    MinLength: 1
  ARNPolicy:
    Description: 'The ARN of the Policy to attachment'
    Type: String
    Default: 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
  TagRole:
    Type: String
    Description: 'Tag: Role of resource.'
    Default: dev
    AllowedValues:
      - dev
      - staging
      - pro
  TagEnvironment:
    Type: String
    Description: 'Tag: Environment where the resource is spawned.'
    Default: dev
    AllowedValues:
      - dev
      - staging
      - pro
  TagSLA:
    Type: String
    Description: 'Tag: Service-level agreement.'
    Default: 24x7
    AllowedValues:
      - '24x7'
      - '8x5'
  TagStartTime:
    Type: String
    Description: 'When is the resource spawned?, ie ''00:00''.'
    Default: '00:00'
  TagEndTime:
    Type: String
    Description: 'When is the resource terminated?, ie ''18:30''.'
    Default: '00:00'
  TagCECO:
    Type: String
    Description: 'Operation owner of resource deployed, ie ''the same as Operation tag''.'
    Default: nebul4ck
  TagOperation:
    Type: String
    Description: 'Operation owner of resource deployed.'
    Default: nebul4ck
    AllowedValues:
      - nebul4ck
  TagCompliance:
    Type: String
    Description: Compliance.
    Default: 'no'
    AllowedValues:
      - 'no'
      - 'yes'
  TagConfidentiality:
    Type: String
    Description: Confidentiality.
    Default: 'no'
    AllowedValues:
      - 'yes'
      - 'no'

##############################################################################################
# Conditions                                                                                 #
##############################################################################################

#Conditions:
#  isNotPublicAccess: !Equals [!Ref S3PublicAccess, Private]
#  isWebSite: !Equals [!Ref S3PublicAccess, PublicRead]

##############################################################################################
# Resources                                                                                  #
##############################################################################################

Resources:
  # Create Role
  EC2AssumeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: IAM Role for enable SSM Managed Instance Core
      RoleName: !Sub '${RoleName}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      ManagedPolicyArns:
        - !Ref ARNPolicy
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Sub '${AccountName}-${RoleName}-role'
        - Key: ApplicationID
          Value: !Sub '${AccountName}-${RoleName}-role'
        - Key: Role
          Value: !Sub '${TagRole}'
        - Key: Environment
          Value: !Sub '${TagEnvironment}'
        - Key: SLA
          Value: !Sub '${TagSLA}'
        - Key: StartTime
          Value: !Sub '${TagStartTime}'
        - Key: EndTime
          Value: !Sub '${TagEndTime}'
        - Key: CECO
          Value: !Sub '${TagCECO}'
        - Key: Operation
          Value: !Sub '${TagOperation}'
        - Key: Compliance
          Value: !Sub '${TagCompliance}'
        - Key: Confidentiality
          Value: !Sub '${TagConfidentiality}'

  InstanceProfile:
    # Create Instance Profile
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles: 
        - !Ref EC2AssumeRole

# Note: Use the InstanceProfileName into ec2 template "IamInstanceProfile" property.